### ISSUE TITLE
Readme vacio

### ISSUE THREAD

**Issue by Saryace** [ANID-GITHUB/CP_PAA#1]
Hola! el README.md esta vacío, no se pueden entender los colnames

**Comment by ANID-GITHUB** [comment]
Estimada Sara,

Esperando que estés muy bien, te comento que la guía de colnames (si te refieres a nombres de columnas) está en el pdf adjunto: en https://github.com/ANID-GITHUB/CP_PAA/blob/main/BBDD_Consulta_PAA.pdf 
Cada nombre de columna contiene una numeración de preguntas (p1, p8, etc.) seguida del texto de la pregunta enunciada de la siguiente manera:

P1_ID de la respuesta
P8_¿Ha leído la Política de Acceso   Abierto; disponible aquí: link?
P11_Sexo
P12_Edad
RANGO ETARIO
P13_Area del conocimiento en la cual se enmarca su quehacer
P14_OCDE
P16_Usted es una:
P17_Pais de residencia
P17_RECAT
P18_Si su país de residencia es Chile;   por favor indique la región
P18_MACROZONA
P19_Nombre Institución
P21_Sector al que pertenece la   institución
P22_Sector económico en el que se   desempeña la institución
P23_area del conocimiento en la cual se   enmarca su quehacer2
P26_Cargo dentro de la institución de   quien responde
P27_CARGO_RECAT
P29_Respecto del objetivo de esta   política ¿Qué tan de acuerdo o en desacuerdo esta usted?
p29_recat
P30_Por favor; ¿podría darnos mas   antecedentes que expliquen su respuesta?
p30_recat
P31_En su opinión; ¿hay otros aspectos   que deberían incluirse dentro del objetivo general?
P32_Si respondió afirmativamente; por   favor; indique cuales serian esos aspectos:
p32_recat
P33_Respecto de los objetivos específicos   de esta política ¿Qué tan de acuerdo o en desacuerdo esta usted?
p33_recat
P35_Por favor; ¿podría darnos mas   antecedentes que expliquen su respuesta?4
p35_recat
P36_En su opinión; ¿hay otros aspectos   que deberían incluirse dentro de los objetivos específicos?
P37_Si respondió afirmativamente; por   favor; indique cuales serian esos aspectos:5
p37_recat
P38_Sobre lo anterior:  Indique su nivel de acuerdo o desacuerdo   respecto a las dos fases de implementación que señala la Política de Acceso   Abierto
p38_recat
P39_Por favor; ¿podría darnos mas   antecedentes que expliquen su respuesta?
p39_recat
P40_En su opinión; ¿hay otros aspectos   que deberían incluirse dentro de la implementación de la Política de Acceso   Abierto?
P41_Si respondió afirmativamente; por   favor; indique cuales serian esos aspectos.
p41_recat
P42_Por favor; señale su nivel de acuerdo   o desacuerdo respecto de esta obligación:
p42_recat
P43_Por favor; ¿podría darnos mas   antecedentes que expliquen su respuesta?6
P43_RECAT
P44_En su opinión; ¿hay otros aspectos   que deberían incluirse dentro de las obligaciones indicadas en el párrafo?
P45_Si respondió afirmativamente; por   favor; indique cuales deberían ser esos aspectos:
P45_RECAT
P46_De acuerdo a lo descrito; señale su   nivel de acuerdo o desacuerdo respecto de esta obligación.
P46_RECAT
P47_Por favor; ¿podría darnos mas   antecedentes que expliquen su respuesta?7
P47_RECAT
P48_En su opinión; ¿hay otros aspectos   que deberían incluirse dentro de las obligaciones indicadas para los datos de   investigación?
P49_Si respondió afirmativamente; por   favor; indique cuales serian esos aspectos:8
P49_RECAT
P50_Por favor; señale su nivel de acuerdo   o desacuerdo respecto de estas acciones:
P50_RECAT
P51_Por favor; ¿podría darnos mas   antecedentes que expliquen su respuesta?9
p51_recat
P52_En su opinión; ¿hay otros aspectos   que deberían incluirse dentro de las acciones que debe ejecutar la ANID para   implementar la Política de Acceso Abierto?
P53_Por favor; indique cuales deberían   ser esos aspectos:
p53_recat
P54_¿Que otros aspectos usted considera   que debiesen ser abordados en la Política de Acceso Abierto y_o en las   acciones para su implementación?
p54_recat

Quedamos atentos a tus consultas/dudas al respecto.

Saludos cordiales,

Agencia Nacional de Investigación y Desarrollo
